### ISSUE TITLE
Injecting IServiceOperations

### ISSUE THREAD

**Issue by thedwillis** [MichaCo/AutorestWithHttpClientFactory#1]
Thanks for the great example! I have it working well in our environment when injecting the Autorest API client directly into the consuming class, however I'm struggling to get it working when injecting an IServiceOperations. Do you know if it is possible? I've tried just injecting the service operation on top of your example, but I'm receiving the following error on startup:

"Unable to resolve service for type 'API.ClientLib.DataApiClient' while attempting to activate 'API.ClientLib.Workspaces'."

**Comment by MichaConrad** [comment]
Hey @thedwillis,
I think it is because the generated ServiceOperations uses the class and not the interface in the constructor

```
internal ServiceOperations(WhateverClient client)
```

My example injects the interface. If you use the implementation instead somewhere, you also have to configure a service in DI for that explicitly.

**Comment by thedwillis** [comment]
Managed to get it working yesterday, for anyone with a similar problem:

```
collection.AddScoped<{IServiceOperation}, {ServiceOperation}>(p => {
    // get configured HttpClient
    var httpClient = (ApiClient)p.GetRequiredService<IApiClient>();
    return new {ServiceOperation}(httpClient);
});
```
